version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: docker_server.dockerfile
    # ports:
    #   - 50051:50051
  nginx:
    image: nginx
    ports:
      - 50051:50051
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro